#ifndef C_SOCKET_CONFIGURATION_H
#define C_SOCKET_CONFIGURATION_H

extern const int MAX_PENDING_CONNECTIONS;
extern const int PORT;
extern const int KEY_VALUE_STORE_SIZE;

extern const int ALLOW_MULTIPLE_CLIENTS;

#endif //C_SOCKET_CONFIGURATION_H